project:
  type: website
  output-dir: docs

website:
  title: "Aida Camacho Ponce de Leon"
  description: "Research, data, cities, energy, and the environment"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
  
      - href: research.qmd
        text: Research
  
      - href: teaching.qmd
        text: Teaching
  
      - href: cv.pdf
        text: CV
  
      - text: Assignments
        menu:
          - href: assign01.qmd
            text: Assignment 1

    right:
      - icon: github
        href: https://github.com/AIDACPL
      - icon: envelope
        href: mailto:dal920987@utdallas.edu

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: false
